### ISSUE TITLE
Add KML crate to org

### ISSUE THREAD

**Issue by pjsier** [georust/meta#27]
I've been working on a KML crate at [`pjsier/kml`](https://github.com/pjsier/kml), and I think it's in good enough shape to move into the georust org. I based the design on the `geojson` crate, and it's mostly focused on compatibility with `geo-types` and basic read/write functionality for common KML elements

If that's alright I can transfer the ownership to georust,  update the license and metadata, and set up the crate publishing team. Based on the guidelines doc would anyone else want to be a user owner for redundancy?

**Comment by michaelkirk** [comment]
Cool @pjsier. I just did a quick perusal, and things look good to me. 

I'd be in favor of including this crate in georust.

**Comment by urschrei** [comment]
Yes, me too.

**Comment by frewsxcv** [comment]
+1 from me!

**Comment by pjsier** [comment]
Sounds great! I'll go ahead and transfer the repo
