### ISSUE TITLE
setup admins@georust.org

### ISSUE THREAD

**Issue by michaelkirk** [georust/meta#28]
re https://github.com/georust/geocoding/pull/50#discussion_r690687908

It'd be good to have this be a list with a few active georusters at the other end so that people have a real life contact.

Who controls the domain - @frewsxcv?

**Comment by michaelkirk** [comment]
Oh wait, maybe it already exists, but it's `mods@georust.org`

 https://github.com/georust/geojson/blob/master/Cargo.toml#L5

**Comment by urschrei** [comment]
Yep, just realised and asked @frewsxcv if we can alias admins@ to mods@

**Comment by michaelkirk** [comment]
Yeah or just use `mods`, I'm fine either way.

**Comment by urschrei** [comment]
I have of course scattered admins@ across various crates. I am very good at this.
