### ISSUE TITLE
Integrate the RINEX crate to the Georust community ?

### ISSUE THREAD

**Issue by gwbres** [georust/meta#31]
Hello,

this follows up the discussion initiated [there](https://github.com/georust/geo/discussions/926)

>We are 2 people working on a [RINEX](https://github.com/gwbres/rinex) crate, and we're in the process of reaching out to communities to see if there is any interest in integrating our crate to a global project. The main objective would be to reach a broader audience, have more people involved in the maintenance, have the code naturally become more stable as time goes by.

Following the discussion,

@lnicola, thank you for your answer

>The way we usually proceed is that you retain admin and crate publishing rights, along with georust “core” (a slowly-growing group of committers to one or more geo crates) 

That would be the ideal scenario to us

> I think the only other condition is adoption of the georust CoC (which is the Rust CoC)

Indeed we did not commit to any CoC until today. I just introduced the default Rust CoC, this can eventually be easily replaced.

Do you foresee anything else that would block moving forward?

Following our roadmap, we should cross by next month the point where all major RINEX formats are supported both in (parser) and out (writer) which would lead to "version 1". We're also in the process of adding Python bindings to reach a broader audience and become a serious alternative to the existing Python library (which for instance, does not support exotic RINEX like we do). That could be a good starting point for a new form of collaboration. We're also not in a hurry and I'd like to have more people from your community share their thoughts on the subject.

see you

**Comment by gwbres** [comment]
Our [latest release](https://github.com/gwbres/rinex/releases) sees major improvements, in particular the stabilization of meaningful calculations and signal visualization methods.

Also the crate takes advantage of Hifitime to support Time scales, Leap seconds and cross the subsecond timestamp precision barrier. For instance, the highest precision required in a RINEX to this day is +/-100ns for physical Observations, and becomes naturally supported.

Finally, IONEX - Ionosphere Maps in RINEX can now be parsed. They represent the electron density in the atmosphere at a given position around the globe. Combining those with the rest of the library will probably unlock countless applications & algorithms

**Comment by michaelkirk** [comment]
Done a while ago! Welcome: https://github.com/georust/rinex
