### ISSUE TITLE
Remove 'rust-' from all repository names?

### ISSUE THREAD

**Issue by frewsxcv** [georust/meta#5]
e.g. `georust/rust-geo`  → `georust/geo`

**Comment by groteworld** [comment]
Do the cargo file just need to be updated after the name change with the new repo? I'm cool with it. There is a little mental mapping involved with figuring out if its for rust but seriously its pretty easy to determine.

**Comment by frewsxcv** [comment]
Yeah, the work here is renaming the repos and updating the Cargo.toml files to reflect the new URLs. GitHub automatically sets up redirects when renaming repos.

**Comment by frewsxcv** [comment]
This is done!
