### ISSUE TITLE
Shapefile crate

### ISSUE THREAD

**Issue by tmontaigu** [georust/meta#6]
Hello,

For the past weeks I've been working on a Rust crate to read Shapefiles [shapefile-rs](https://github.com/tmontaigu/shapefile-rs).

I saw that this organization already owns a crate with the name "shapefile", but it seems incomplete & hasn't been updated on crates.io for 3 years.

I was wondering if could get the access to the "shapefile" name on crates.io for the crate that a wrote ?

**Comment by frewsxcv** [comment]
Just sent you an invite to become an owner of the `shapefile` crate name! If you're ever interested in transferring your repo over to the GeoRust GitHub organization, let me know 👋 No pressure!

**Comment by tmontaigu** [comment]
Thanks for responding,

However I haven't received (yet?) the invitation to become an owner.

As for transferring the crate to the GeoRust It sounds like a good idea, I'll probably do that once I find that I have something stable and good enough

**Comment by frewsxcv** [comment]
```
/p/t/shapefile (master|✔) $ cargo owner -a tmontaigu
    Updating crates.io index
       Owner user tmontaigu has been invited to be an owner of crate shapefile
```

I just tried again – did you get an invite?

**Comment by tmontaigu** [comment]
Yes, thank you 👍
